### ISSUE TITLE
License to use image in wikipedia?

### ISSUE THREAD

**Issue by canadaduane** [temporaer/myriaworld#1]
I'd like to add the example image of the myriahedral projection to wikipedia. Would that be ok? If so, how would you like to license your work? Perhaps [CC-BY](https://en.wikipedia.org/wiki/Wikipedia:File_copyright_tags/All#Creative_Commons) or BSD? (see file uploaded here: https://en.wikipedia.org/wiki/File:Myriahedral_projection.png)

**Comment by temporaer** [comment]
Sure, I'll put the code under BSD so let's give the same license to the image for simplicity.

**Comment by canadaduane** [comment]
Great, thanks! And nice work :)
